spring:
  jpa:
    # 전송 쿼리 확인
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa

  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  issuer: admin@email.com
  secret_key: sample-key
